name: publish-master

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Release')"
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Show github environment variables
        run: |
          echo ${NODE_AUTH_TOKEN}
          echo ${GITHUB_REF}
          echo ${GITHUB_BASE_REF}
          echo ${GITHUB_REF_NAME}
          echo ${GITHUB_HEAD_REF}
          echo ${GITHUB_ACTOR}
          echo ${GITHUB_ACTION}
          echo ${GITHUB_REPOSITORY}
      - name: Increment version
        run: npx @padcom/semver-inc@latest ${GITHUB_HEAD_REF}
