name: publish-master

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Show github environment variables
        run: echo ${NODE_AUTH_TOKEN}
        run: echo ${GITHUB_REF}
        run: echo ${GITHUB_BASE_REF}
        run: echo ${GITHUB_ACTOR}
        run: echo ${GITHUB_ACTION}
        run: echo ${GITHUB_REPOSITORY}
